[package]
name = "loft"
version = "0.0.1-alpha.1"
edition = "2021"
license = "MIT"

description = "..."
repository = "https://github.com/themackabu/loft"

[lib]
name = "loft"
path = "src/loft/lib.rs"

[[bin]]
name = "loft"
path = "src/loft.rs"

[dependencies]
macros-rs = "1.4.1"
