[tasks]
test.script = "cargo run tests/%{arg.1}.lo"
run.script = "sh -c \"RUSTFLAGS='-C target-cpu=native' cargo run --release %{arg.1}\""

[tasks.test-all]
path = "tests"
script = "bash -c 'for file in *.lo; do maid test -q ${file%.lo}; done'"
